### PR TITLE
Adding support for lists with views from other DDocs

### PR DESCRIPTION
**Pull request by mroeder**
According to the official CouchDB documentation, _lists_ also can use views of a secondary, different design document (see http://docs.couchdb.org/en/1.6.1/api/ddoc/render.html#db-design-design-doc-list-list-name-other-ddoc-view-name).
This pull request together with pouchdb/express-pouchdb#285 fix that issue.

### CODE REVIEW

**Comment by marten-de-vries** [comment]
Thanks for your PR! It seems like a nice feature to add.

In #2, I made a start at a pretty thorough test suite for this module. It's just not merged yet (really need to do so soon, it's stalled but the stuff that's in there is stable). I did ran your PR against it, which gave me two issues (these are regressions):

```
  10 passing (797ms)
  2 failing

  1) Sync list tests args:

      AssertionError: expected '/test/_design/test/_list/args/test/ids?a=b' to equal '/test/_design/test/_list/args/ids?a=b'
      + expected - actual

      -/test/_design/test/_list/args/test/ids?a=b
      +/test/_design/test/_list/args/ids?a=b

      at features.js:64:23
      at run (/home/marten/git/pouchdb-plugin-helper/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:104:47)
      at /home/marten/git/pouchdb-plugin-helper/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:115:28
      at flush (/home/marten/git/pouchdb-plugin-helper/node_modules/babel-polyfill/node_modules/core-js/modules/$.microtask.js:19:5)

  2) http list basics:

      AssertionError: expected '/pouchdb-plugin-helper-db/_design/test/_list/args/test/ids?a=b' to equal '/pouchdb-plugin-helper-db/_design/test/_list/args/ids?a=b'
      + expected - actual

      -/pouchdb-plugin-helper-db/_design/test/_list/args/test/ids?a=b
      +/pouchdb-plugin-helper-db/_design/test/_list/args/ids?a=b

      at http.js:20:25
      at run (/home/marten/git/pouchdb-plugin-helper/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:104:47)
      at /home/marten/git/pouchdb-plugin-helper/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:115:28
      at flush (/home/marten/git/pouchdb-plugin-helper/node_modules/babel-polyfill/node_modules/core-js/modules/$.microtask.js:19:5)
```

Those would need to be fixed before merging. I tested by checking out #2 (as the largest PR of the two), and then ran:

``` bash
curl https://patch-diff.githubusercontent.com/raw/pouchdb/pouchdb-list/pull/4.patch | git am -
```

**Comment by mroeder** [comment]
I cannot get the PR #2 http tests to run correctly on my computer (OSX, Node.JS 4.2.6) - even without incorporating my changes:

```
1) http "before each" hook for "list basics":
     Error: connect ECONNREFUSED 127.0.0.1:5984
      at onError (node_modules/pouchdb-plugin-helper/node_modules/pouchdb/lib/index.js:2533:18)
      at Request._callback (node_modules/pouchdb-plugin-helper/node_modules/pouchdb/lib/index.js:2571:14)
      at self.callback (node_modules/pouchdb-plugin-helper/node_modules/pouchdb/node_modules/request/request.js:198:22)
      at Request.onRequestError (node_modules/pouchdb-plugin-helper/node_modules/pouchdb/node_modules/request/request.js:820:8)
      at Socket.socketErrorListener (_http_client.js:258:9)
      at emitErrorNT (net.js:1256:8)
```

I even tried with a git checkout of `pouchdb-plugin-helper` and downgrading node to 0.10 (as set in `.travis.yml` but that didn't change anything. What am I missing?

**Comment by marten-de-vries** [comment]
You're missing a CouchDB installation. I should probably document that somewhere.

**Comment by mroeder** [comment]
Oops. I saw that in `.travis.yml` too but was wondering about it.
Anyway, that was an easy fix. I would also add a test case for the PR once you have the modernize branch into the master.

**Comment by marten-de-vries** [comment]
Nice job. I decided to go ahead and merge both PRs, and to just open follow up issues. A test would be very welcome as a follow up, it would help with #3.

Thanks! c59079d30403649c31cda33d485188df09272eed

**Comment by marten-de-vries** [comment]
I'm planning to release 1.1.0 as soon as Travis builds the latest PR, btw. It passes offline, but I want the second opinion before releasing to npm.

**Pull request closed without merging**
